on:
  release:
    types: [published]
jobs:
  deploy:
    uses: sogeor/workflows/.github/workflows/release.yml@master
    secrets: inherit
    with:
      DOCKER_IMAGE_NAME: ${{ vars.DOCKER_IMAGE_NAME }}
